### ISSUE TITLE
Update Readme + Changelog for 0.5.0

### ISSUE THREAD

**Issue by Speedy1991** [Speedy1991/Flask-FileUpload#12]
@gouthambs can you give me example settings + a short description what these settings are for, please?
Needed for the changelog + readme

```
FILEUPLOAD_S3_BUCKET
FILEUPLOAD_S3_ACL
```
Thank you

**Comment by gouthambs** [comment]
@Speedy1991 Sorry for not getting back earlier. Here are the settings descriptions:


FILEUPLOAD_S3_BUCKET is the name of the S3 bucket
FILEUPLOAD_S3_ACL is the S3 permission for the files uploaded to S3, default is `public-read`. Options are `public-read`, `private`, `public-read-write`, `authenticated-read`, `aws-exec-read`, `bucket-owner-read`, `bucket-owner-full-control`.


Sample settings:

`FILEUPLOAD_S3_BUCKET` = 'sample-bucket-name'
`FILEUPLOAD_S3_ACL` = 'public-read'

**Comment by Speedy1991** [comment]
Just released 0.5.0 with s3 storage.
Thanks for your help!
