### ISSUE TITLE
Flask-FileUpload URL Mismatch

### ISSUE THREAD

**Issue by gouthambs** [Speedy1991/Flask-FileUpload#4]
- I ran the `Flask-Blogging` `example/main.py` example. 
- I upload a file through the flask-fleupload image link

![screenshot from 2017-05-06 20-48-26](https://cloud.githubusercontent.com/assets/4218827/25777790/81b8f990-329d-11e7-9ca4-30115510f785.png)

You can see the link in the `Path` column says `http://localhost:8000/static/upload/...` while the actual link of the image is `http://localhost:8000/static/fileupload/...`.

**Comment by Speedy1991** [comment]
fixed with #6
Released [0.4.1](https://github.com/Speedy1991/Flask-FileUpload/tree/0.4.1)
