### ISSUE TITLE
Uploading Images With Same Filename Fails

### ISSUE THREAD

**Issue by gouthambs** [Speedy1991/Flask-FileUpload#5]
When you upload image with the same filename, there is an error. This can be an issue in general because it is likely that people will upload similarly named files. There are two approaches to address this:
- Convert filename to some id and make it unique 
- Or handle conflict resolution so the uploads always happen as handled [here](https://github.com/maxcountryman/flask-uploads/blob/master/flask_uploads.py#L433)

**Comment by Speedy1991** [comment]
The error is on purpose.
- I can't make plain unique id's, cause the table is filterable by name, it would be kinda usless if only random hashes are present.
- I don't want to make a database dependency where i could map id -> file_name


I could add a random generated hash, maybe 6 chars,  to the renaming field, which get's autofilled by "choose file"

### Pro:
- User don't have to worry about unique name, it's combined out of name + unique hash (e.g. "__my_file_name_ze7as2.png__")
- User have still full control about naming, cause he just could change the filename anyway, but get's the existing error on duplicate filename

What do you think about this?

**Comment by Speedy1991** [comment]
I can add something like [this](https://github.com/Speedy1991/Flask-FileUpload/commit/5862d0ffab143713953927b62a4ab495765369ec) if u want. It can be enabled via config _FILEUPLOAD_RANDOM_FILE_APPENDIX_

**Comment by gouthambs** [comment]
I agree you don't want to add database dependency. I like the idea of unique name with a random hash. That should solve the issue. Can you also think about standardizing the names to lower case? This will make the file names a bit more uniform I think.

**Comment by Speedy1991** [comment]
> Can you also think about standardizing the names to lower case?

i think thats a good point, i ll add it with the next release i think

**Comment by Speedy1991** [comment]
What do you think about something like [this](http://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case)

**Comment by gouthambs** [comment]
This is a simple and elegant solution. :+1:

**Comment by Speedy1991** [comment]
is included with 0.4.2, just released
