### ISSUE TITLE
S3 based storage for FileUpload

### ISSUE THREAD

**Issue by gouthambs** [Speedy1991/Flask-FileUpload#8]
@Speedy1991 
I am thinking about a S3 based storage for Flask-Blogging. The end goal is to be able to run Flask-Blogging based example on AWS-Lambda. To go along with this, an S3 based FileUpload storage, and ability to inject other storages would be necessary. Just wanted to get a sense of what you think.

**Comment by Speedy1991** [comment]
I havn't worked with S3/AWS yet. I am kind of busy atm and have no time to develop this myself. In August/September I can have a look - i'll definitly check this stuff out if i have some time left :)

**Comment by Speedy1991** [comment]
Do i need something like [this](https://github.com/mardix/flask-cloudy)? That looks like i don't need to have any knowlege of S3, just how to provide a interface to push/pull files to/from it?

**Comment by gouthambs** [comment]
This looks interesting. I use boto3 but have no preference. If you have time try it out.

**Comment by gouthambs** [comment]
New PR #11

**Comment by Speedy1991** [comment]
ty! I guess i ll release a new version within the next week

**Comment by gouthambs** [comment]
Sounds good. Thanks.
